Fetching data operation using HttpClient.
Fetching URL does not work tho. The commit happen because the following error was solved:
ERROR NullInjectorError: R3InjectorError(Standalone[_ProductListComponent])[_ProductService -> _ProductService -> _HttpClient -> _HttpClient]:
  NullInjectorError: No provider for _HttpClient!